package com.hss01248.accountcache.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hss01248.accountcache.DebugAccount;

import com.hss01248.accountcache.db.DebugAccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig debugAccountDaoConfig;

    private final DebugAccountDao debugAccountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        debugAccountDaoConfig = daoConfigMap.get(DebugAccountDao.class).clone();
        debugAccountDaoConfig.initIdentityScope(type);

        debugAccountDao = new DebugAccountDao(debugAccountDaoConfig, this);

        registerDao(DebugAccount.class, debugAccountDao);
    }
    
    public void clear() {
        debugAccountDaoConfig.clearIdentityScope();
    }

    public DebugAccountDao getDebugAccountDao() {
        return debugAccountDao;
    }

}
